pub_rate: 1.0
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  sound_play:
    type: diagnostic_aggregator/GenericAnalyzer
    path: SoundPlay
    startswith: sound_play
  breakers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Breakers
    analyzers:
      base_breaker:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base Breaker
        startswith: base_breaker
      battery_breaker:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Battery Breaker
        startswith: battery_breaker
      computer_breaker:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Computer Breaker
        startswith: computer_breaker
      supply_breaker:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Supply Breaker
        startswith: supply_breaker
  motors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Motor Control Boards
    analyzers:
      l_wheel:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Left Wheel
        startswith: l_wheel
      r_wheel:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Right Wheel
        startswith: r_wheel
  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      base_breaker:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Sick TIM551 Laser
        startswith: sick_tim
  peripherals:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Peripherals
    analyzers:
      joy:
        type: diagnostic_aggregator/GenericAnalyzer
        path: PS3 Controller
        find_and_remove_prefix: "joy:"
  system:
    type: diagnostic_aggregator/AnalyzerGroup
    path: System
    analyzers:
      mainboard:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Mainboard
        startswith: Mainboard
      charger:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Charger
        startswith: Charger
